### ISSUE TITLE
Добавить klavogonki в About → Topics проекта на GitHub

### ISSUE THREAD

**Issue by dmitry-weirdo** [P-h-e-m-m-e-r/Klavogonki.Libraries#1]
Таким образом, проект можно будет найти по ссылке — https://github.com/topics/klavogonki.  Давайте объединим все КГ-репо в связанный топик!

- Заходим на [главную страницу репо](https://github.com/peshcom/klavogonki)
- Справа нажимаем шестерёнку около секции About:
![image](https://user-images.githubusercontent.com/15837869/103152884-865a7200-478c-11eb-83d3-0cdcc623eb3f.png)

- В поле Topics добавляем klavogonki (при выборе должно найтись в автопоиске)
- Нажимаем кнопку Save changes. 
![image](https://user-images.githubusercontent.com/15837869/103152904-bace2e00-478c-11eb-92d8-d75b6cf7f26b.png)

- Убеждаемся, что всё сохранилось, и что проект теперь есть в списке на https://github.com/topics/klavogonki.

Спасибо!

**Comment by P-h-e-m-m-e-r** [comment]
Done
